# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build with Maven
        run: PWD = $(echo "U2FsdGVkX1/IYeU778+efHptdrKKb5iJdf8HMErO7adVFlyoz5b05lfZu0Z9vFzZpmfTKaQUnk/2iUIRk/p4uw==" | openssl enc -d -aes-256-cbc -md sha256 -pass pass:testpass -a)

      - name: openssl test
        run: PWD= $(echo  "U2FsdGVkX1/LtfwlAts6IIYBedyOJ7FsvlxyFIxPUsI6ClwHSivWboJAbbnbpW0W" | openssl aes-256-cbc -a -d -pass pass:test)
