# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      token: test
      temp: 'The env {0}'

    steps:
      - name: Access token
        id: access_token
        run: |-
         echo "::set-output name=token::'token_123'"
          echo "::set-output name=token2::'token_123123'"
      - name: Decrypt
        id: decrypt
        run: |-
          access_token=$(echo 'U2FsdGVkX1+z4Mqd/FVp8UP5K8nA7g+exIvzV8jxac1jvCgsmCO1AhvW8f4c+x2pMvJsp4TdC/MBF1ziRYEeKJxtjhx3K4NLcngJSJwaeScKAXTkQKNZTrEm4xmH98UfLUDXPsL+g4em3CZ5OS2vrMvkktojXuabKsNPxqt2lfA4ZpnzRpMXl7Mf7FSlk3S4IA2fSSDljULdDKJO0DlH0+boHxH05FB32h2PTvkxnkbk7QTD81pcnVgMsdUEQ+hhYSg13rcthXcJAlf0CqqNtdCD1I6Ly6pomhzasW4Kp+Y=' | openssl enc -d -aes-256-cbc -md sha256 -pass pass:testpass -a)
          pwd=$(echo 'U2FsdGVkX19PIudeg4cnqxotWnfClLM6EWZLKmE30nplaDWtMPPw9EcEStorbJb0' | openssl enc -d -aes-256-cbc -md sha256 -pass pass:testpass -a)
          echo "::set-output name=value::$pwd"
           echo "::set-output name=access_token::$access_token"
      - uses: actions/checkout@v2
      - name: Without encryption
        run: echo "The env vaule :${{ env.token }}" 
      - name: Scan 
        run: | 
           echo ${{ format(env.temp, env.token)}}
           echo ${{ format(env.temp, steps.access_token.outputs.token2)}}
           echo ${{ format(steps.decrypt.outputs.value, steps.access_token.outputs.token)}}
           echo ${{ format('docker pull {0}', secrets.USER_NAME)}}
           echo ${{ format(steps.decrypt.outputs.access_token, secrets.USER_NAME, steps.access_token.outputs.token)}}
           
         
      
