# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      token: test
      temp: 'The env {0}'

    steps:
      - name: Access token
        id: access_token
        run: |-
         echo "::set-output name=token::'The env {0}'"
      - uses: actions/checkout@v2
      - name: Without encryption
        run: echo "The env vaule :${{ env.token }}" 
      - name: With encryption 
        run: | 
           pwd=$(echo 'U2FsdGVkX19PIudeg4cnqxotWnfClLM6EWZLKmE30nplaDWtMPPw9EcEStorbJb0' | openssl enc -d -aes-256-cbc -md sha256 -pass pass:testpass -a)
           echo $pwd
           echo ${{ format(env.temp, env.token)}}
           echo ${{ format(steps.access_token.outputs.token, env.token)}}
         
      
